name: Create Release and Push Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.AutoTagger.outputs.new_tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Minor version for each merge
      id: AutoTagger
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.token}}
        WITH_V: true
    - name: Check tag format
      run: echo ${{ steps.AutoTagger.outputs.new_tag }}

  push-docker-image:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check tag format
        run: echo ${{ needs.create-release.outputs.new_tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: server
          push: true
          tags: |
            rayahh/3tier-back:${{ needs.create-release.outputs.new_tag }}
          
